version: "3"
services:
  follower-syncer:
    build: .
    volumes:
      - ./:/src/follower-syncer
      - source-certs:/opt/source/conjur/etc/ssl
      - destination-certs:/opt/destination/conjur/etc/ssl

  dap-source:
    image: registry2.itci.conjur.net/conjur-appliance:${VERSION}
    container_name: dap-source
    ports:
      - "443:443"
    expose:
      - "443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - source-certs:/opt/conjur/etc/ssl

  dap-destination:
    image: registry2.itci.conjur.net/conjur-appliance:${VERSION}
    container_name: dap-destination
    ports:
      - "444:443"
    expose:
      - "443"
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - destination-certs:/opt/conjur/etc/ssl

volumes:
  source-certs:
  destination-certs:
